In [1]:
import pandas as pd
matchesdata=pd.read_csv('/home/kiran/Documents/ipl/matches.csv')

In this notebook we analyse some of the key insights related to the player performance of all ipl matches. Some of the most important questions that need to be answered are who is the most successful bowler ,who is the most successful batsman and what is the impact on toss on a team winning a match at a particular venue. Dataset considered is a free opensource dataset from kaggle
https://www.kaggle.com/patrickb1912/ipl-complete-dataset-20082020

Key Findings
We see that Lasith Malinga is the most successful bowler with most number of wickets,Andrew russel has the highest strike rate, Johnny Baristow has the highest average and Chennai super Kings has the higest win rate after winning a toss and deciding to bat.

How we arrived at the findings...Please follow the code if interested

In [61]:
#Reading in the data

In [2]:
deliveriesdata=pd.read_csv('/home/kiran/Documents/ipl/deliveries.csv')

In [63]:
#Examining the data . The data is at an individual match level which needs to be aggregated for any significant analysis

In [64]:
deliveriesdata.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,0,0,0
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,0,0,0
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,0,0,0
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,0,0,0
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,0,0,0

In [4]:
deliveriesdata

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
5,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,6,S Dhawan,DA Warner,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
6,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,7,S Dhawan,DA Warner,TS Mills,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
7,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,1,S Dhawan,DA Warner,A Choudhary,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
8,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,2,DA Warner,S Dhawan,A Choudhary,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
9,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,3,DA Warner,S Dhawan,A Choudhary,0,...,0,0,1,0,0,1,1,NaN,NaN,NaN
10,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,4,DA Warner,S Dhawan,A Choudhary,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
11,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,5,DA Warner,S Dhawan,A Choudhary,0,...,0,0,0,0,0,0,0,DA Warner,caught,Mandeep Singh
12,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,6,MC Henriques,S Dhawan,A Choudhary,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
13,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,7,MC Henriques,S Dhawan,A Choudhary,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
14,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,1,S Dhawan,MC Henriques,TS Mills,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
15,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,2,MC Henriques,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
16,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,3,MC Henriques,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
17,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,4,MC Henriques,S Dhawan,TS Mills,0,...,0,0,0,0,3,0,3,NaN,NaN,NaN
18,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,5,S Dhawan,MC Henriques,TS Mills,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
19,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,6,MC Henriques,S Dhawan,TS Mills,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
20,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,4,1,MC Henriques,S Dhawan,YS Chahal,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
21,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,4,2,MC Henriques,S Dhawan,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
22,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,4,3,S Dhawan,MC Henriques,YS Chahal,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
23,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,4,4,S Dhawan,MC Henriques,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
24,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,4,5,MC Henriques,S Dhawan,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
25,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,4,6,S Dhawan,MC Henriques,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
26,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,5,1,S Dhawan,MC Henriques,S Aravind,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
27,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,5,2,MC Henriques,S Dhawan,S Aravind,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
28,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,5,3,S Dhawan,MC Henriques,S Aravind,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
29,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,5,4,MC Henriques,S Dhawan,S Aravind,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179048,11415,2,Chennai Super Kings,Mumbai Indians,16,1,DJ Bravo,SR Watson,SL Malinga,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
179049,11415,2,Chennai Super Kings,Mumbai Indians,16,2,DJ Bravo,SR Watson,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179050,11415,2,Chennai Super Kings,Mumbai Indians,16,3,SR Watson,DJ Bravo,SL Malinga,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
179051,11415,2,Chennai Super Kings,Mumbai Indians,16,4,SR Watson,DJ Bravo,SL Malinga,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
179052,11415,2,Chennai Super Kings,Mumbai Indians,16,5,SR Watson,DJ Bravo,SL Malinga,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
179053,11415,2,Chennai Super Kings,Mumbai Indians,16,6,SR Watson,DJ Bravo,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179054,11415,2,Chennai Super Kings,Mumbai Indians,17,1,SR Watson,DJ Bravo,JJ Bumrah,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179055,11415,2,Chennai Super Kings,Mumbai Indians,17,2,DJ Bravo,SR Watson,JJ Bumrah,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179056,11415,2,Chennai Super Kings,Mumbai Indians,17,3,SR Watson,DJ Bravo,JJ Bumrah,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
179057,11415,2,Chennai Super Kings,Mumbai Indians,17,4,SR Watson,DJ Bravo,JJ Bumrah,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
179058,11415,2,Chennai Super Kings,Mumbai Indians,17,5,SR Watson,DJ Bravo,JJ Bumrah,0,...,1,0,0,0,1,1,2,NaN,NaN,NaN
179059,11415,2,Chennai Super Kings,Mumbai Indians,17,6,DJ Bravo,SR Watson,JJ Bumrah,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179060,11415,2,Chennai Super Kings,Mumbai Indians,18,1,DJ Bravo,SR Watson,KH Pandya,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179061,11415,2,Chennai Super Kings,Mumbai Indians,18,2,SR Watson,DJ Bravo,KH Pandya,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
179062,11415,2,Chennai Super Kings,Mumbai Indians,18,3,SR Watson,DJ Bravo,KH Pandya,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
179063,11415,2,Chennai Super Kings,Mumbai Indians,18,4,SR Watson,DJ Bravo,KH Pandya,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
179064,11415,2,Chennai Super Kings,Mumbai Indians,18,5,SR Watson,DJ Bravo,KH Pandya,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
179065,11415,2,Chennai Super Kings,Mumbai Indians,18,6,SR Watson,DJ Bravo,KH Pandya,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179066,11415,2,Chennai Super Kings,Mumbai Indians,19,1,SR Watson,DJ Bravo,JJ Bumrah,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179067,11415,2,Chennai Super Kings,Mumbai Indians,19,2,DJ Bravo,SR Watson,JJ Bumrah,0,...,0,0,0,0,0,0,0,DJ Bravo,caught,Q de Kock
179068,11415,2,Chennai Super Kings,Mumbai Indians,19,3,RA Jadeja,SR Watson,JJ Bumrah,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179069,11415,2,Chennai Super Kings,Mumbai Indians,19,4,RA Jadeja,SR Watson,JJ Bumrah,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
179070,11415,2,Chennai Super Kings,Mumbai Indians,19,5,RA Jadeja,SR Watson,JJ Bumrah,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179071,11415,2,Chennai Super Kings,Mumbai Indians,19,6,RA Jadeja,SR Watson,JJ Bumrah,0,...,4,0,0,0,4,4,8,NaN,NaN,NaN
179072,11415,2,Chennai Super Kings,Mumbai Indians,20,1,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179073,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179074,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179076,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179077,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [ ]:
#What are the columns do we have. A close examination gives us the information we have on all the matches

In [5]:
deliveriesdata.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batsman', 'non_striker', 'bowler', 'is_super_over', 'wide_runs',
       'bye_runs', 'legbye_runs', 'noball_runs', 'penalty_runs',
       'batsman_runs', 'extra_runs', 'total_runs', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='object')

In [ ]:
#Just like any data , this data needs to be cleaned up.lets clean the data and treat them for missing values

In [6]:
deliveriesdata['player_dismissed']

0               NaN
1               NaN
2               NaN
3               NaN
4               NaN
5               NaN
6               NaN
7               NaN
8               NaN
9               NaN
10              NaN
11        DA Warner
12              NaN
13              NaN
14              NaN
15              NaN
16              NaN
17              NaN
18              NaN
19              NaN
20              NaN
21              NaN
22              NaN
23              NaN
24              NaN
25              NaN
26              NaN
27              NaN
28              NaN
29              NaN
            ...
179048          NaN
179049          NaN
179050          NaN
179051          NaN
179052          NaN
179053          NaN
179054          NaN
179055          NaN
179056          NaN
179057          NaN
179058          NaN
179059          NaN
179060          NaN
179061          NaN
179062          NaN
179063          NaN
179064          NaN
179065          NaN
179066          NaN
179067     DJ Bravo
179068          NaN
179069          NaN
179070          NaN
179071          NaN
179072          NaN
179073          NaN
179074          NaN
179075    SR Watson
179076          NaN
179077    SN Thakur
Name: player_dismissed, Length: 179078, dtype: object

In [65]:
deliveriesdata=deliveriesdata.fillna(0)#All missing vlaues are treated to 0

In [8]:
dismissals=deliveriesdata[deliveriesdata['batsman']==deliveriesdata['player_dismissed']]

In [9]:
dismissals

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
11,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,5,DA Warner,S Dhawan,A Choudhary,0,...,0,0,0,0,0,0,0,DA Warner,caught,Mandeep Singh
64,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,11,3,S Dhawan,MC Henriques,STR Binny,0,...,0,0,0,0,0,0,0,S Dhawan,caught,Sachin Baby
94,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,16,2,MC Henriques,Yuvraj Singh,YS Chahal,0,...,0,0,0,0,0,0,0,MC Henriques,caught,Sachin Baby
116,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,19,4,Yuvraj Singh,DJ Hooda,TS Mills,0,...,0,0,0,0,0,0,0,Yuvraj Singh,bowled,0
160,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,6,4,Mandeep Singh,CH Gayle,Rashid Khan,0,...,0,0,0,0,0,0,0,Mandeep Singh,bowled,0
165,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,7,3,CH Gayle,TM Head,DJ Hooda,0,...,0,0,0,0,0,0,0,CH Gayle,caught,DA Warner
199,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,12,4,KM Jadhav,TM Head,MC Henriques,0,...,0,0,0,0,1,0,1,KM Jadhav,run out,BCJ Cutting
206,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,13,5,TM Head,SR Watson,Rashid Khan,0,...,0,0,0,0,0,0,0,TM Head,caught,Yuvraj Singh
211,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,14,4,Sachin Baby,SR Watson,Bipul Sharma,0,...,0,0,0,0,0,0,0,Sachin Baby,caught,MC Henriques
230,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,17,5,STR Binny,SR Watson,B Kumar,0,...,0,0,0,0,0,0,0,STR Binny,caught,Yuvraj Singh
234,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,18,3,SR Watson,S Aravind,A Nehra,0,...,0,0,0,0,0,0,0,SR Watson,caught,MC Henriques
235,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,18,4,S Aravind,TS Mills,A Nehra,0,...,0,0,0,0,0,0,0,S Aravind,bowled,0
242,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,5,TS Mills,YS Chahal,B Kumar,0,...,0,0,0,0,0,0,0,TS Mills,caught,DA Warner
274,2,1,Mumbai Indians,Rising Pune Supergiant,5,2,PA Patel,JC Buttler,Imran Tahir,0,...,0,0,0,0,0,0,0,PA Patel,bowled,0
287,2,1,Mumbai Indians,Rising Pune Supergiant,7,3,RG Sharma,JC Buttler,Imran Tahir,0,...,0,0,0,0,0,0,0,RG Sharma,bowled,0
289,2,1,Mumbai Indians,Rising Pune Supergiant,7,5,JC Buttler,N Rana,Imran Tahir,0,...,0,0,0,0,0,0,0,JC Buttler,lbw,0
316,2,1,Mumbai Indians,Rising Pune Supergiant,12,1,AT Rayudu,N Rana,R Bhatia,0,...,0,0,0,0,0,0,0,AT Rayudu,caught and bowled,0
330,2,1,Mumbai Indians,Rising Pune Supergiant,14,2,KH Pandya,N Rana,R Bhatia,0,...,0,0,0,0,0,0,0,KH Pandya,caught,MS Dhoni
343,2,1,Mumbai Indians,Rising Pune Supergiant,16,3,N Rana,KA Pollard,A Zampa,0,...,0,0,0,0,0,0,0,N Rana,caught,R Bhatia
361,2,1,Mumbai Indians,Rising Pune Supergiant,19,2,KA Pollard,HH Pandya,BA Stokes,0,...,0,0,0,0,0,0,0,KA Pollard,caught,MA Agarwal
392,2,2,Rising Pune Supergiant,Mumbai Indians,4,1,MA Agarwal,AM Rahane,MJ McClenaghan,0,...,0,0,0,0,0,0,0,MA Agarwal,caught,RG Sharma
434,2,2,Rising Pune Supergiant,Mumbai Indians,11,1,AM Rahane,SPD Smith,TG Southee,0,...,0,0,0,0,0,0,0,AM Rahane,caught,N Rana
467,2,2,Rising Pune Supergiant,Mumbai Indians,16,2,BA Stokes,SPD Smith,HH Pandya,0,...,0,0,0,0,0,0,0,BA Stokes,caught,TG Southee
514,3,1,Gujarat Lions,Kolkata Knight Riders,4,1,JJ Roy,BB McCullum,PP Chawla,0,...,0,0,0,0,0,0,0,JJ Roy,caught,YK Pathan
544,3,1,Gujarat Lions,Kolkata Knight Riders,9,1,BB McCullum,SK Raina,Kuldeep Yadav,0,...,0,0,0,0,0,0,0,BB McCullum,lbw,0
557,3,1,Gujarat Lions,Kolkata Knight Riders,11,2,AJ Finch,SK Raina,Kuldeep Yadav,0,...,0,0,0,0,0,0,0,AJ Finch,caught,Kuldeep Yadav
615,3,1,Gujarat Lions,Kolkata Knight Riders,20,5,KD Karthik,SK Raina,TA Boult,0,...,0,0,0,0,0,0,0,KD Karthik,caught,Kuldeep Yadav
717,4,1,Rising Pune Supergiant,Kings XI Punjab,1,5,MA Agarwal,AM Rahane,Sandeep Sharma,0,...,0,0,0,0,0,0,0,MA Agarwal,bowled,0
750,4,1,Rising Pune Supergiant,Kings XI Punjab,7,2,AM Rahane,SPD Smith,T Natarajan,0,...,0,0,0,0,0,0,0,AM Rahane,caught,MP Stoinis
762,4,1,Rising Pune Supergiant,Kings XI Punjab,9,2,SPD Smith,BA Stokes,MP Stoinis,0,...,0,0,0,0,0,0,0,SPD Smith,caught,M Vohra
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178557,11413,2,Delhi Capitals,Sunrisers Hyderabad,15,4,AR Patel,RR Pant,Rashid Khan,0,...,0,0,0,0,0,0,0,AR Patel,caught,WP Saha
178578,11413,2,Delhi Capitals,Sunrisers Hyderabad,19,1,S Rutherford,RR Pant,B Kumar,0,...,0,0,0,0,0,0,0,S Rutherford,caught,Mohammad Nabi
178583,11413,2,Delhi Capitals,Sunrisers Hyderabad,19,6,RR Pant,K Paul,B Kumar,0,...,0,0,0,0,0,0,0,RR Pant,caught,Mohammad Nabi
178589,11413,2,Delhi Capitals,Sunrisers Hyderabad,20,5,A Mishra,K Paul,K Ahmed,0,...,0,0,0,0,0,0,0,A Mishra,obstructing the field,0
178606,11414,1,Delhi Capitals,Chennai Super Kings,3,3,P Shaw,S Dhawan,DL Chahar,0,...,0,0,0,0,0,0,0,P Shaw,lbw,0
178623,11414,1,Delhi Capitals,Chennai Super Kings,6,2,S Dhawan,C Munro,Harbhajan Singh,0,...,0,0,0,0,0,0,0,S Dhawan,caught,MS Dhoni
178644,11414,1,Delhi Capitals,Chennai Super Kings,9,5,C Munro,SS Iyer,RA Jadeja,0,...,0,0,0,0,0,0,0,C Munro,caught,DJ Bravo
178660,11414,1,Delhi Capitals,Chennai Super Kings,12,3,SS Iyer,RR Pant,Imran Tahir,0,...,0,0,0,0,0,0,0,SS Iyer,caught,SK Raina
178668,11414,1,Delhi Capitals,Chennai Super Kings,13,5,AR Patel,RR Pant,DJ Bravo,0,...,0,0,0,0,0,0,0,AR Patel,caught,Imran Tahir
178687,11414,1,Delhi Capitals,Chennai Super Kings,16,5,S Rutherford,RR Pant,Harbhajan Singh,0,...,0,0,0,0,0,0,0,S Rutherford,caught,SR Watson
178700,11414,1,Delhi Capitals,Chennai Super Kings,18,6,K Paul,RR Pant,DJ Bravo,0,...,0,0,0,0,0,0,0,K Paul,bowled,0
178705,11414,1,Delhi Capitals,Chennai Super Kings,19,4,RR Pant,A Mishra,DL Chahar,0,...,0,0,0,0,0,0,0,RR Pant,caught,DJ Bravo
178710,11414,1,Delhi Capitals,Chennai Super Kings,20,3,TA Boult,A Mishra,RA Jadeja,0,...,0,0,0,0,0,0,0,TA Boult,bowled,0
178776,11414,2,Chennai Super Kings,Delhi Capitals,11,2,F du Plessis,SR Watson,TA Boult,0,...,0,0,0,0,0,0,0,F du Plessis,caught,K Paul
178789,11414,2,Chennai Super Kings,Delhi Capitals,13,2,SR Watson,SK Raina,A Mishra,0,...,0,0,0,0,0,0,0,SR Watson,caught,TA Boult
178811,11414,2,Chennai Super Kings,Delhi Capitals,16,6,SK Raina,AT Rayudu,AR Patel,0,...,0,0,0,0,0,0,0,SK Raina,bowled,0
178827,11414,2,Chennai Super Kings,Delhi Capitals,19,4,MS Dhoni,AT Rayudu,I Sharma,0,...,0,0,0,0,0,0,0,MS Dhoni,caught,K Paul
178859,11415,1,Mumbai Indians,Chennai Super Kings,5,5,Q de Kock,RG Sharma,SN Thakur,0,...,0,0,0,0,0,0,0,Q de Kock,caught,MS Dhoni
178863,11415,1,Mumbai Indians,Chennai Super Kings,6,2,RG Sharma,AS Yadav,DL Chahar,0,...,0,0,0,0,0,0,0,RG Sharma,caught,MS Dhoni
178901,11415,1,Mumbai Indians,Chennai Super Kings,12,2,AS Yadav,Ishan Kishan,Imran Tahir,0,...,0,0,0,0,0,0,0,AS Yadav,bowled,0
178908,11415,1,Mumbai Indians,Chennai Super Kings,13,3,KH Pandya,Ishan Kishan,SN Thakur,0,...,0,0,0,0,0,0,0,KH Pandya,caught,SN Thakur
178921,11415,1,Mumbai Indians,Chennai Super Kings,15,4,Ishan Kishan,KA Pollard,Imran Tahir,0,...,0,0,0,0,0,0,0,Ishan Kishan,caught,SK Raina
178943,11415,1,Mumbai Indians,Chennai Super Kings,19,2,HH Pandya,KA Pollard,DL Chahar,0,...,0,0,0,0,0,0,0,HH Pandya,lbw,0
178945,11415,1,Mumbai Indians,Chennai Super Kings,19,4,RD Chahar,KA Pollard,DL Chahar,0,...,0,0,0,0,0,0,0,RD Chahar,caught,F du Plessis
178977,11415,2,Chennai Super Kings,Mumbai Indians,4,6,F du Plessis,SR Watson,KH Pandya,0,...,0,0,0,0,0,0,0,F du Plessis,stumped,Q de Kock
179012,11415,2,Chennai Super Kings,Mumbai Indians,10,2,SK Raina,SR Watson,RD Chahar,0,...,0,0,0,0,0,0,0,SK Raina,lbw,0
179019,11415,2,Chennai Super Kings,Mumbai Indians,11,3,AT Rayudu,SR Watson,JJ Bumrah,0,...,0,0,0,0,0,0,0,AT Rayudu,caught,Q de Kock
179067,11415,2,Chennai Super Kings,Mumbai Indians,19,2,DJ Bravo,SR Watson,JJ Bumrah,0,...,0,0,0,0,0,0,0,DJ Bravo,caught,Q de Kock
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179077,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,0,0,0,SN Thakur,lbw,0

In [10]:
dismissals_bowler=dismissals.groupby(['bowler']).size().reset_index()

In [ ]:
#We will first see the number of wickets taken by each bowler

In [11]:
dismissals_bowler

                bowler    0
0       A Ashish Reddy   18
1           A Chandila   11
2          A Choudhary    5
3           A Flintoff    2
4             A Joseph    6
5             A Kumble   47
6             A Mishra  160
7             A Mithun    7
8              A Nehra  115
9                A Nel    1
10               A Roy    1
11             A Singh   32
12           A Symonds   21
13            A Uniyal    2
14             A Zampa   19
15           AA Chavan    8
16     AA Jhunjhunwala    1
17           AA Noffke    1
18          AB Agarkar   30
19            AB Dinda   79
20         AB McDonald   14
21        AC Gilchrist    1
22           AC Thomas   14
23            AC Voges    1
24      AD Mascarenhas   19
25          AD Mathews   28
26          AD Russell   58
27            AF Milne    5
28          AG Murtaza   11
29            AJ Finch    1
..                 ...  ...
320         T Thushara    9
321           TA Boult   40
322         TG Southee   31
323           TL Suman    6
324         TM Dilshan    5
325            TM Head    3
326       TP Sudhindra    1
327           TS Mills    5
328           UT Yadav  127
329           Umar Gul   14
330     V Chakravarthy    1
331            V Kohli    4
332     V Pratap Singh   11
333           V Sehwag    6
334          V Shankar    2
335           VR Aaron   43
336          VRV Singh   14
337           VS Malik    6
338          VY Mahesh   21
339            WA Mota    4
340         WD Parnell   27
341         WPUJC Vaas   20
342  Washington Sundar   16
343            Y Nagar    4
344    Y Venugopal Rao    7
345         YA Abdulla   15
346          YK Pathan   46
347          YS Chahal  101
348       Yuvraj Singh   38
349             Z Khan  113

[350 rows x 2 columns]

In [66]:
#We will see the number of balls bowled by each bowler

In [12]:
dismissals_ballsbowled=deliveriesdata.groupby(['bowler'])['ball'].count().reset_index()

In [13]:
dismissals_ballsbowled

                bowler  ball
0       A Ashish Reddy   270
1           A Chandila   234
2          A Choudhary   108
3          A Dananjaya    25
4           A Flintoff    66
5             A Joseph    55
6             A Kumble   983
7             A Mishra  3172
8             A Mithun   312
9              A Nehra  1974
10               A Nel    18
11               A Roy    15
12             A Singh   551
13           A Symonds   540
14            A Uniyal    38
15             A Zampa   225
16           AA Chavan   255
17     AA Jhunjhunwala    88
18             AA Kazi    13
19           AA Noffke    25
20          AB Agarkar   820
21            AB Dinda  1589
22         AB McDonald   188
23        AC Gilchrist     1
24           AC Thomas   327
25            AC Voges    56
26      AD Mascarenhas   310
27          AD Mathews   807
28          AD Russell  1072
29            AF Milne   115
..                 ...   ...
375           TL Suman   152
376         TM Dilshan   275
377            TM Head    48
378       TP Sudhindra    74
379           TS Mills   111
380       Tejas Baroka    21
381           UT Yadav  2605
382           Umar Gul   153
383     V Chakravarthy    18
384            V Kohli   264
385     V Pratap Singh   211
386           V Sehwag   138
387          V Shankar    92
388           VR Aaron   978
389          VRV Singh   371
390           VS Malik   212
391        VS Yeligati    32
392          VY Mahesh   359
393            WA Mota    75
394         WD Parnell   601
395         WPUJC Vaas   288
396  Washington Sundar   358
397   Y Gnaneswara Rao     6
398            Y Nagar    72
399    Y Venugopal Rao   222
400         YA Abdulla   222
401          YK Pathan  1184
402          YS Chahal  1841
403       Yuvraj Singh   882
404             Z Khan  2276

[405 rows x 2 columns]

In [ ]:
#Next we will see the runs given by each bowler

In [14]:
dismissals_runsgiven=deliveriesdata.groupby(['bowler'])['total_runs'].sum().reset_index()

In [15]:
dismissialsbolwerruns=pd.merge(dismissals_ballsbowled,dismissals_runsgiven)

In [67]:
#Combining the runs given and the wickets taken per bowler

In [16]:
wicketsperbowler=pd.merge(dismissialsbolwerruns,dismissals_bowler)

In [17]:
wicketsperbowler

                bowler  ball  total_runs    0
0       A Ashish Reddy   270         400   18
1           A Chandila   234         245   11
2          A Choudhary   108         144    5
3           A Flintoff    66         106    2
4             A Joseph    55          94    6
5             A Kumble   983        1089   47
6             A Mishra  3172        3850  160
7             A Mithun   312         477    7
8              A Nehra  1974        2537  115
9                A Nel    18          31    1
10               A Roy    15          14    1
11             A Singh   551         769   32
12           A Symonds   540         694   21
13            A Uniyal    38          67    2
14             A Zampa   225         281   19
15           AA Chavan   255         339    8
16     AA Jhunjhunwala    88         130    1
17           AA Noffke    25          41    1
18          AB Agarkar   820        1174   30
19            AB Dinda  1589        2103   79
20         AB McDonald   188         263   14
21        AC Gilchrist     1           0    1
22           AC Thomas   327         416   14
23            AC Voges    56          76    1
24      AD Mascarenhas   310         365   19
25          AD Mathews   807        1095   28
26          AD Russell  1072        1584   58
27            AF Milne   115         185    5
28          AG Murtaza   269         322   11
29            AJ Finch    44          67    1
..                 ...   ...         ...  ...
320         T Thushara   144         164    9
321           TA Boult   802        1168   40
322         TG Southee   932        1340   31
323           TL Suman   152         198    6
324         TM Dilshan   275         368    5
325            TM Head    48          81    3
326       TP Sudhindra    74         137    1
327           TS Mills   111         157    5
328           UT Yadav  2605        3640  127
329           Umar Gul   153         198   14
330     V Chakravarthy    18          35    1
331            V Kohli   264         371    4
332     V Pratap Singh   211         300   11
333           V Sehwag   138         236    6
334          V Shankar    92         154    2
335           VR Aaron   978        1392   43
336          VRV Singh   371         549   14
337           VS Malik   212         268    6
338          VY Mahesh   359         511   21
339            WA Mota    75          98    4
340         WD Parnell   601         731   27
341         WPUJC Vaas   288         364   20
342  Washington Sundar   358         467   16
343            Y Nagar    72         125    4
344    Y Venugopal Rao   222         338    7
345         YA Abdulla   222         311   15
346          YK Pathan  1184        1443   46
347          YS Chahal  1841        2416  101
348       Yuvraj Singh   882        1092   38
349             Z Khan  2276        2860  113

[350 rows x 4 columns]

In [18]:
wicketsperbowler.columns

Index(['bowler', 'ball', 'total_runs', 0], dtype='object')

In [19]:
wicketsperbowler.columns=['bowler','ballsbowled','totalrunsconceded','numberofdismissals']

In [20]:
wicketsperbowler

                bowler  ballsbowled  totalrunsconceded  numberofdismissals
0       A Ashish Reddy          270                400                  18
1           A Chandila          234                245                  11
2          A Choudhary          108                144                   5
3           A Flintoff           66                106                   2
4             A Joseph           55                 94                   6
5             A Kumble          983               1089                  47
6             A Mishra         3172               3850                 160
7             A Mithun          312                477                   7
8              A Nehra         1974               2537                 115
9                A Nel           18                 31                   1
10               A Roy           15                 14                   1
11             A Singh          551                769                  32
12           A Symonds          540                694                  21
13            A Uniyal           38                 67                   2
14             A Zampa          225                281                  19
15           AA Chavan          255                339                   8
16     AA Jhunjhunwala           88                130                   1
17           AA Noffke           25                 41                   1
18          AB Agarkar          820               1174                  30
19            AB Dinda         1589               2103                  79
20         AB McDonald          188                263                  14
21        AC Gilchrist            1                  0                   1
22           AC Thomas          327                416                  14
23            AC Voges           56                 76                   1
24      AD Mascarenhas          310                365                  19
25          AD Mathews          807               1095                  28
26          AD Russell         1072               1584                  58
27            AF Milne          115                185                   5
28          AG Murtaza          269                322                  11
29            AJ Finch           44                 67                   1
..                 ...          ...                ...                 ...
320         T Thushara          144                164                   9
321           TA Boult          802               1168                  40
322         TG Southee          932               1340                  31
323           TL Suman          152                198                   6
324         TM Dilshan          275                368                   5
325            TM Head           48                 81                   3
326       TP Sudhindra           74                137                   1
327           TS Mills          111                157                   5
328           UT Yadav         2605               3640                 127
329           Umar Gul          153                198                  14
330     V Chakravarthy           18                 35                   1
331            V Kohli          264                371                   4
332     V Pratap Singh          211                300                  11
333           V Sehwag          138                236                   6
334          V Shankar           92                154                   2
335           VR Aaron          978               1392                  43
336          VRV Singh          371                549                  14
337           VS Malik          212                268                   6
338          VY Mahesh          359                511                  21
339            WA Mota           75                 98                   4
340         WD Parnell          601                731                  27
341         WPUJC Vaas          288                364                  20
342  Washington Sundar          358                467                  16
343            Y Nagar           72                125                   4
344    Y Venugopal Rao          222                338                   7
345         YA Abdulla          222                311                  15
346          YK Pathan         1184               1443                  46
347          YS Chahal         1841               2416                 101
348       Yuvraj Singh          882               1092                  38
349             Z Khan         2276               2860                 113

[350 rows x 4 columns]

In [56]:
wicketsperbowler.sort_values('numberofdismissals',ascending=False)

,bowler,ballsbowled,totalrunsconceded,numberofdismissals,runsperwicket,ballsperwicket
292,SL Malinga,2974,3511,181,19.397790,16.430939
6,A Mishra,3172,3850,160,24.062500,19.825000
83,DJ Bravo,2711,3733,159,23.477987,17.050314
111,Harbhajan Singh,3451,4050,157,25.796178,21.980892
229,PP Chawla,3157,4153,153,27.143791,20.633987
47,B Kumar,2707,3264,137,23.824818,19.759124
298,SP Narine,2600,2939,130,22.607692,20.000000
234,R Ashwin,3016,3391,129,26.286822,23.379845
328,UT Yadav,2605,3640,127,28.661417,20.511811
245,R Vinay Kumar,2186,3043,118,25.788136,18.525424
8,A Nehra,1974,2537,115,22.060870,17.165217
246,RA Jadeja,2541,3221,114,28.254386,22.289474
349,Z Khan,2276,2860,113,25.309735,20.141593
347,YS Chahal,1841,2416,101,23.920792,18.227723
299,SR Watson,2137,2751,100,27.510000,21.370000
97,DW Steyn,2207,2454,98,25.040816,22.520408
218,P Kumar,2637,3342,97,34.453608,27.185567
254,RP Singh,1874,2417,96,25.177083,19.520833
230,PP Ojha,1945,2399,94,25.521277,20.691489
196,MM Sharma,1770,2457,93,26.419355,19.032258
128,JA Morkel,1807,2409,90,26.766667,20.077778
117,IK Pathan,2113,2711,90,30.122222,23.477778
307,Sandeep Sharma,1546,1967,87,22.609195,17.770115
95,DS Kulkarni,1830,2461,87,28.287356,21.034483
136,JJ Bumrah,1798,2299,85,27.047059,21.152941
180,M Morkel,1699,2136,85,25.129412,19.988235
118,Imran Tahir,1249,1656,81,20.444444,15.419753
167,L Balaji,1574,2083,81,25.716049,19.432099
130,JD Unadkat,1541,2244,80,28.050000,19.262500
19,AB Dinda,1589,2103,79,26.620253,20.113924
...,...,...,...,...,...,...
232,Pankaj Singh,311,472,11,42.909091,28.272727
261,S Badree,263,329,11,29.909091,23.909091
209,N Saini,300,434,11,39.454545,27.272727
332,V Pratap Singh,211,300,11,27.272727,19.181818
295,SM Pollock,280,307,11,27.909091,25.454545
204,Mohammad Nabi,271,314,11,28.545455,24.636364
285,SC Ganguly,280,370,11,33.636364,25.454545
159,KP Appanna,222,291,10,29.100000,22.200000
262,S Curran,207,336,10,33.600000,20.700000
85,DJ Hussey,323,485,10,48.500000,32.300000
55,BCJ Cutting,288,434,10,43.400000,28.800000
129,JD Ryder,241,314,9,34.888889,26.777778
32,AM Nayar,239,323,9,35.888889,26.555556
53,BAW Mendis,248,306,9,34.000000,27.555556
283,SB Styris,222,278,9,30.888889,24.666667
197,MN Samuels,219,285,9,31.666667,24.333333
15,AA Chavan,255,339,8,42.375000,31.875000
153,KC Cariappa,224,350,8,43.750000,28.000000
182,M Ntini,213,257,8,32.125000,26.625000
63,C de Grandhomme,230,338,7,48.285714,32.857143
344,Y Venugopal Rao,222,338,7,48.285714,31.714286
7,A Mithun,312,477,7,68.142857,44.571429
337,VS Malik,212,268,6,44.666667,35.333333
277,S Tyagi,220,304,6,50.666667,36.666667
266,S Kaushik,210,304,6,50.666667,35.000000
84,DJ Hooda,233,318,6,53.000000,38.833333
324,TM Dilshan,275,368,5,73.600000,55.000000
127,J Yadav,226,248,5,49.600000,45.200000
139,JO Holder,228,313,5,62.600000,45.600000
331,V Kohli,264,371,4,92.750000,66.000000

Lasith Malinga is the highest wickettaker in IPL. He has also conceded the least runs per wicket. That means he is a real asset to any team as a bowler. No wonder he is so highly rated in IPL

In [71]:
#Lets look at the batsman , the runs they scored ,the number of balls they faced

In [23]:
batsmandata=deliveriesdata.groupby(['batsman'])['total_runs'].sum().reset_index()

In [24]:
batsmandata_ballsfaced=deliveriesdata.groupby(['batsman'])['ball'].count().reset_index()

In [25]:
batsmandata_ballsfaced

                  batsman  ball
0          A Ashish Reddy   196
1              A Chandila     7
2                A Chopra    75
3             A Choudhary    20
4             A Dananjaya     5
5              A Flintoff    57
6                 A Hales   119
7                A Joseph    13
8                A Kumble    49
9                A Mishra   410
10               A Mithun    26
11               A Mukund    23
12                A Nehra    63
13                A Singh    10
14              A Symonds   781
15               A Turner    11
16               A Uniyal     7
17                A Zampa     8
18            AA Bilakhia    88
19              AA Chavan    11
20        AA Jhunjhunwala   218
21              AA Noffke    12
22             AB Agarkar   160
23              AB Barath    43
24               AB Dinda    50
25            AB McDonald   103
26         AB de Villiers  2977
27            AC Blizzard    91
28           AC Gilchrist  1555
29              AC Thomas    19
..                    ...   ...
486               V Kohli  4211
487        V Pratap Singh     1
488              V Sehwag  1833
489             V Shankar   429
490                VH Zol    26
491              VR Aaron    63
492             VRV Singh     3
493              VS Malik     7
494           VS Yeligati     2
495            VVS Laxman   271
496             VY Mahesh    28
497          Vishnu Vinod    26
498              W Jaffer   129
499               WA Mota    76
500            WD Parnell    80
501               WP Saha  1382
502            WPUJC Vaas    73
503     Washington Sundar    56
504  X Thalaivan Sargunam    17
505      Y Gnaneswara Rao    18
506               Y Nagar   271
507       Y Venugopal Rao   865
508            YA Abdulla     1
509             YK Pathan  2334
510             YS Chahal    49
511           YV Takawale   183
512         Yashpal Singh    67
513           Younis Khan     7
514          Yuvraj Singh  2207
515                Z Khan   141

[516 rows x 2 columns]

In [26]:
batsmandata=pd.merge(batsmandata,batsmandata_ballsfaced,left_on='batsman',right_on='batsman',how='inner')

In [27]:
batsmandata=pd.merge(batsmandata,dismissals,left_on='batsman',right_on='batsman',how='inner')

In [28]:
batsmandata.columns

Index(['batsman', 'total_runs', 'ball', 'dismissals'], dtype='object')

In [29]:
batsmandata.columns=['batsman', 'total_runs','numberofballsfaced','numberofdismissals']

In [ ]:
#Looking at all batsman ,their runs scored ,the number of balls they faced and the number of times they have got out

In [30]:
batsmandata

                  batsman  total_runs  numberofballsfaced  numberofdismissals
0          A Ashish Reddy         288                 196                  15
1                A Chopra          58                  75                   5
2             A Choudhary          25                  20                   1
3              A Flintoff          72                  57                   2
4                 A Hales         156                 119                   6
5                A Kumble          42                  49                   2
6                A Mishra         408                 410                  27
7                A Mithun          37                  26                   5
8                A Mukund          20                  23                   2
9                 A Nehra          49                  63                   6
10                A Singh           3                  10                   4
11              A Symonds        1028                 781                  24
12               A Turner           5                  11                   3
13               A Uniyal           4                   7                   1
14                A Zampa           5                   8                   2
15            AA Bilakhia          78                  88                   5
16              AA Chavan          12                  11                   1
17        AA Jhunjhunwala         235                 218                  12
18              AA Noffke          11                  12                   1
19             AB Agarkar         193                 160                   8
20              AB Barath          44                  43                   2
21               AB Dinda          30                  50                   9
22            AB McDonald         130                 103                   5
23         AB de Villiers        4583                2977                 102
24            AC Blizzard         126                  91                   7
25           AC Gilchrist        2215                1555                  75
26              AC Thomas          20                  19                   2
27               AC Voges         190                 143                   4
28         AD Mascarenhas          81                  79                   9
29             AD Mathews         765                 599                  28
..                    ...         ...                 ...                 ...
450              Umar Gul          44                  19                   3
451               V Kohli        5616                4211                 142
452        V Pratap Singh           0                   1                   1
453              V Sehwag        2915                1833                  95
454             V Shankar         595                 429                  17
455                VH Zol          29                  26                   2
456              VR Aaron          51                  63                   3
457             VRV Singh           5                   3                   1
458              VS Malik           9                   7                   1
459           VS Yeligati           2                   2                   1
460            VVS Laxman         296                 271                  16
461             VY Mahesh          21                  28                   2
462          Vishnu Vinod          19                  26                   3
463              W Jaffer         139                 129                   7
464               WA Mota          63                  76                   5
465            WD Parnell          74                  80                   9
466               WP Saha        1862                1382                  73
467            WPUJC Vaas          84                  73                   7
468     Washington Sundar          86                  56                   5
469  X Thalaivan Sargunam          10                  17                   1
470      Y Gnaneswara Rao          20                  18                   1
471               Y Nagar         309                 271                  14
472       Y Venugopal Rao        1051                 865                  42
473             YK Pathan        3404                2334                 105
474             YS Chahal          24                  49                   4
475           YV Takawale         207                 183                   8
476         Yashpal Singh          49                  67                   4
477           Younis Khan           3                   7                   1
478          Yuvraj Singh        2895                2207                 107
479                Z Khan         121                 141                  14

[480 rows x 4 columns]

In [31]:
batsmandata['strikerate']=(batsmandata['total_runs']/batsmandata['numberofballsfaced'])*100

In [32]:
batsmandata['average']=batsmandata['total_runs']/batsmandata['numberofdismissals']

In [33]:
batsmandata['strikerate'].describe()

count    480.000000
mean     109.850164
std       36.667004
min        0.000000
25%       91.641566
50%      116.450713
75%      133.358550
max      231.578947
Name: strikerate, dtype: float64

In [34]:
batsmandata=batsmandata[batsmandata['numberofballsfaced']>100]

In [35]:
topstrikerates=batsmandata.sort_values(by='strikerate',ascending=False)

In [72]:
#We will get the strike rate and average of each batsman. The strike rate is an important parameter in a fast paced game like IPL. The quicker you score , the greater the value a batsman adds to the team

In [36]:
topstrikerates.head(20)

,batsman,total_runs,numberofballsfaced,numberofdismissals,strikerate,average
31,AD Russell,1527,803,40,190.161893,38.175000
408,SP Narine,856,481,40,177.962578,21.400000
227,M Ali,325,183,10,177.595628,32.500000
67,BCJ Cutting,253,146,10,173.287671,25.300000
94,CR Brathwaite,205,120,13,170.833333,15.769231
283,N Pooran,186,110,6,169.090909,31.000000
345,RR Pant,1855,1104,47,168.025362,39.468085
165,J Bairstow,487,293,8,166.211604,60.875000
141,GJ Maxwell,1485,902,59,164.634146,25.169492
149,HH Pandya,1200,736,37,163.043478,32.432432
85,CH Morris,540,339,19,159.292035,28.421053
453,V Sehwag,2915,1833,95,159.028914,30.684211
173,JC Buttler,1501,954,37,157.337526,40.567568
84,CH Gayle,4873,3131,109,155.637177,44.706422
23,AB de Villiers,4583,2977,102,153.946926,44.931373
75,Bipul Sharma,190,124,6,153.225806,31.666667
201,KH Pandya,960,635,32,151.181102,30.000000
257,MJ Lumb,297,198,10,150.000000,29.700000
52,Ankit Sharma,171,114,10,150.000000,17.100000
195,KA Pollard,2940,1964,96,149.694501,30.625000

We see that Andre Russel has the highest strike rate across all matches,considering all batsman who have faced more than 100 balls

In [37]:
average=batsmandata.sort_values(by='average',ascending=False)

In [38]:
average.head(20)

,batsman,total_runs,numberofballsfaced,numberofdismissals,strikerate,average
165,J Bairstow,487,293,8,166.211604,60.875000
265,MN van Wyk,175,135,3,129.629630,58.333333
306,PD Collingwood,213,159,4,133.962264,53.250000
27,AC Voges,190,143,4,132.867133,47.500000
150,HM Amla,600,418,13,143.540670,46.153846
103,DA Warner,4975,3398,108,146.409653,46.064815
269,MS Dhoni,4691,3318,102,141.380350,45.990196
294,OA Shah,550,405,12,135.802469,45.833333
23,AB de Villiers,4583,2977,102,153.946926,44.931373
84,CH Gayle,4873,3131,109,155.637177,44.706422
185,JP Duminy,2143,1680,48,127.559524,44.645833
325,R Parag,178,133,4,133.834586,44.500000
205,KL Rahul,2087,1465,47,142.457338,44.404255
223,LMP Simmons,1127,878,26,128.359909,43.346154
261,ML Hayden,1205,839,28,143.623361,43.035714
11,A Symonds,1028,781,24,131.626120,42.833333
394,SE Marsh,2612,1913,62,136.539467,42.129032
252,MEK Hussey,2064,1648,49,125.242718,42.122449
209,KS Williamson,1362,981,33,138.837920,41.272727
173,JC Buttler,1501,954,37,157.337526,40.567568

#Johnny baristow has the highest average in IPL. On a average he is sure to give you a good contribution on a given  day

In [45]:
matchesdata

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
5,6,2017,Hyderabad,2017-04-09,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,9,Rashid Khan,"Rajiv Gandhi International Stadium, Uppal",A Deshmukh,NJ Llong,NaN
6,7,2017,Mumbai,2017-04-09,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,N Rana,Wankhede Stadium,Nitin Menon,CK Nandan,NaN
7,8,2017,Indore,2017-04-10,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,normal,0,Kings XI Punjab,0,8,AR Patel,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
8,9,2017,Pune,2017-04-11,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Delhi Daredevils,97,0,SV Samson,Maharashtra Cricket Association Stadium,AY Dandekar,S Ravi,NaN
9,10,2017,Mumbai,2017-04-12,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,JJ Bumrah,Wankhede Stadium,Nitin Menon,CK Nandan,NaN
10,11,2017,Kolkata,2017-04-13,Kings XI Punjab,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,8,SP Narine,Eden Gardens,A Deshmukh,NJ Llong,NaN
11,12,2017,Bangalore,2017-04-14,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,KA Pollard,M Chinnaswamy Stadium,KN Ananthapadmanabhan,AK Chaudhary,NaN
12,13,2017,Rajkot,2017-04-14,Rising Pune Supergiant,Gujarat Lions,Gujarat Lions,field,normal,0,Gujarat Lions,0,7,AJ Tye,Saurashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
13,14,2017,Kolkata,2017-04-15,Kolkata Knight Riders,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Kolkata Knight Riders,17,0,RV Uthappa,Eden Gardens,AY Dandekar,NJ Llong,NaN
14,15,2017,Delhi,2017-04-15,Delhi Daredevils,Kings XI Punjab,Delhi Daredevils,bat,normal,0,Delhi Daredevils,51,0,CJ Anderson,Feroz Shah Kotla,YC Barde,Nitin Menon,NaN
15,16,2017,Mumbai,2017-04-16,Gujarat Lions,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,6,N Rana,Wankhede Stadium,A Nand Kishore,S Ravi,NaN
16,17,2017,Bangalore,2017-04-16,Rising Pune Supergiant,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Rising Pune Supergiant,27,0,BA Stokes,M Chinnaswamy Stadium,KN Ananthapadmanabhan,C Shamshuddin,NaN
17,18,2017,Delhi,2017-04-17,Delhi Daredevils,Kolkata Knight Riders,Delhi Daredevils,bat,normal,0,Kolkata Knight Riders,0,4,NM Coulter-Nile,Feroz Shah Kotla,Nitin Menon,CK Nandan,NaN
18,19,2017,Hyderabad,2017-04-17,Sunrisers Hyderabad,Kings XI Punjab,Kings XI Punjab,field,normal,0,Sunrisers Hyderabad,5,0,B Kumar,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,A Deshmukh,NaN
19,20,2017,Rajkot,2017-04-18,Royal Challengers Bangalore,Gujarat Lions,Gujarat Lions,field,normal,0,Royal Challengers Bangalore,21,0,CH Gayle,Saurashtra Cricket Association Stadium,S Ravi,VK Sharma,NaN
20,21,2017,Hyderabad,2017-04-19,Sunrisers Hyderabad,Delhi Daredevils,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,15,0,KS Williamson,"Rajiv Gandhi International Stadium, Uppal",CB Gaffaney,NJ Llong,NaN
21,22,2017,Indore,2017-04-20,Kings XI Punjab,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,8,JC Buttler,Holkar Cricket Stadium,M Erasmus,C Shamshuddin,NaN
22,23,2017,Kolkata,2017-04-21,Kolkata Knight Riders,Gujarat Lions,Gujarat Lions,field,normal,0,Gujarat Lions,0,4,SK Raina,Eden Gardens,CB Gaffaney,Nitin Menon,NaN
23,24,2017,Mumbai,2017-04-22,Mumbai Indians,Delhi Daredevils,Delhi Daredevils,field,normal,0,Mumbai Indians,14,0,MJ McClenaghan,Wankhede Stadium,A Nand Kishore,S Ravi,NaN
24,25,2017,Pune,2017-04-22,Sunrisers Hyderabad,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,6,MS Dhoni,Maharashtra Cricket Association Stadium,AY Dandekar,A Deshmukh,NaN
25,26,2017,Rajkot,2017-04-23,Kings XI Punjab,Gujarat Lions,Gujarat Lions,field,normal,0,Kings XI Punjab,26,0,HM Amla,Saurashtra Cricket Association Stadium,AK Chaudhary,M Erasmus,NaN
26,27,2017,Kolkata,2017-04-23,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Kolkata Knight Riders,82,0,NM Coulter-Nile,Eden Gardens,CB Gaffaney,CK Nandan,NaN
27,28,2017,Mumbai,2017-04-24,Rising Pune Supergiant,Mumbai Indians,Mumbai Indians,field,normal,0,Rising Pune Supergiant,3,0,BA Stokes,Wankhede Stadium,A Nand Kishore,S Ravi,NaN
28,29,2017,Pune,2017-04-26,Rising Pune Supergiant,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,7,RV Uthappa,Maharashtra Cricket Association Stadium,AY Dandekar,NJ Llong,NaN
29,30,2017,Bangalore,2017-04-27,Royal Challengers Bangalore,Gujarat Lions,Gujarat Lions,field,normal,0,Gujarat Lions,0,7,AJ Tye,M Chinnaswamy Stadium,AK Chaudhary,C Shamshuddin,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,11322,2019,Mumbai,15/04/19,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,5,SL Malinga,Wankhede Stadium,Marais Erasmus,Nitin Menon,Nanda Kishore
727,11323,2019,Mohali,16/04/19,Kings XI Punjab,Rajasthan Royals,Rajasthan Royals,field,normal,0,Kings XI Punjab,12,0,R Ashwin,IS Bindra Stadium,Anil Chaudhary,Vineet Kulkarni,S Ravi
728,11324,2019,Hyderabad,17/04/19,Chennai Super Kings,Sunrisers Hyderabad,Chennai Super Kings,bat,normal,0,Sunrisers Hyderabad,0,6,DA Warner,Rajiv Gandhi Intl. Cricket Stadium,Ian Gould,Ulhas Gandhe,C Shamshuddin
729,11325,2019,Delhi,18/04/19,Mumbai Indians,Delhi Capitals,Mumbai Indians,bat,normal,0,Mumbai Indians,40,0,HH Pandya,Feroz Shah Kotla Ground,Nigel Llong,Bruce Oxenford,Anil Chaudhary
730,11326,2019,Kolkata,19/04/19,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Royal Challengers Bangalore,10,0,V Kohli,Eden Gardens,Ian Gould,Nitin Menon,Anil Dandekar
731,11327,2019,Jaipur,20/04/19,Mumbai Indians,Rajasthan Royals,Rajasthan Royals,field,normal,0,Rajasthan Royals,0,5,SPD Smith,Sawai Mansingh Stadium,S Ravi,Yeshwant Barde,O Nandan
732,11328,2019,Delhi,20/04/19,Kings XI Punjab,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,5,SS Iyer,Feroz Shah Kotla Ground,Ulhas Gandhe,C Shamshuddin,Bruce Oxenford
733,11329,2019,Hyderabad,21/04/19,Kolkata Knight Riders,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,9,K Ahmed,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Nigel Llong,Ian Gould
734,11330,2019,Bengaluru,21/04/19,Royal Challengers Bangalore,Chennai Super Kings,Chennai Super Kings,field,normal,0,Royal Challengers Bangalore,1,0,PA Patel,M. Chinnaswamy Stadium,Vineet Kulkarni,Rod Tucker,Anil Chaudhary
735,11331,2019,Jaipur,22/04/19,Rajasthan Royals,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,6,RR Pant,Sawai Mansingh Stadium,S Ravi,Nanda Kishore,Yeshwant Barde
736,11332,2019,Chennai,23/04/19,Sunrisers Hyderabad,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,SR Watson,M. A. Chidambaram Stadium,Nigel Llong,Anil Chaudhary,Vineet Kulkarni
737,11333,2019,Bengaluru,24/04/19,Royal Challengers Bangalore,Kings XI Punjab,Kings XI Punjab,field,normal,0,Royal Challengers Bangalore,17,0,AB de Villiers,M. Chinnaswamy Stadium,Bruce Oxenford,C Shamshuddin,Rod Tucker
738,11334,2019,Kolkata,25/04/19,Kolkata Knight Riders,Rajasthan Royals,Rajasthan Royals,field,normal,0,Rajasthan Royals,0,3,VR Aaron,Eden Gardens,Ian Gould,Anil Dandekar,Nitin Menon
739,11335,2019,Chennai,26/04/19,Mumbai Indians,Chennai Super Kings,Chennai Super Kings,field,normal,0,Mumbai Indians,46,0,RG Sharma,M. A. Chidambaram Stadium,Nigel Llong,Anil Chaudhary,Vineet Kulkarni
740,11336,2019,Jaipur,27/04/19,Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,field,normal,0,Rajasthan Royals,0,7,JD Unadkat,Sawai Mansingh Stadium,Yeshwant Barde,Nand Kishore,Sundaram Ravi
741,11337,2019,Delhi,28/04/19,Delhi Capitals,Royal Challengers Bangalore,Delhi Capitals,bat,normal,0,Delhi Capitals,16,0,S Dhawan,Feroz Shah Kotla Ground,Bruce Oxenford,KN Ananthapadmanabhan,C Shamshuddin
742,11338,2019,Kolkata,28/04/19,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Kolkata Knight Riders,34,0,AD Russell,Eden Gardens,Ian Gould,Nitin Menon,Anil Dandekar
743,11339,2019,Hyderabad,29/04/19,Sunrisers Hyderabad,Kings XI Punjab,Kings XI Punjab,field,normal,0,Sunrisers Hyderabad,45,0,DA Warner,Rajiv Gandhi Intl. Cricket Stadium,S Ravi,O Nandan,Nanda Kishore
744,11340,2019,Bengaluru,30/04/19,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,no result,0,NaN,0,0,NaN,M. Chinnaswamy Stadium,Nigel Llong,Ulhas Gandhe,Anil Chaudhary
745,11341,2019,Chennai,01/05/19,Chennai Super Kings,Delhi Capitals,Delhi Capitals,field,normal,0,Chennai Super Kings,80,0,MS Dhoni,M. A. Chidambaram Stadium,Anil Dandekar,Nitin Menon,Ian Gould
746,11342,2019,Mumbai,02/05/19,Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians,bat,tie,0,Mumbai Indians,0,0,JJ Bumrah,Wankhede Stadium,S Ravi,O Nandan,Nanda Kishore
747,11343,2019,Mohali,03/05/19,Kings XI Punjab,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,7,S Gill,IS Bindra Stadium,Bruce Oxenford,C Shamshuddin,KN Ananthapadmanabhan
748,11344,2019,Delhi,04/05/19,Rajasthan Royals,Delhi Capitals,Rajasthan Royals,bat,normal,0,Delhi Capitals,0,5,A Mishra,Feroz Shah Kotla Ground,Ian Gould,Anil Dandekar,Nitin Menon
749,11345,2019,Bengaluru,04/05/19,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,S Hetmyer,M. Chinnaswamy Stadium,Nigel Llong,Anil Chaudhary,Ulhas Gandhe
750,11346,2019,Mohali,05/05/19,Chennai Super Kings,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,KL Rahul,IS Bindra Stadium,KN Ananthapadmanabhan,C Shamshuddin,Bruce Oxenford
751,11347,2019,Mumbai,05/05/19,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,9,HH Pandya,Wankhede Stadium,Nanda Kishore,O Nandan,S Ravi
752,11412,2019,Chennai,07/05/19,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Mumbai Indians,0,6,AS Yadav,M. A. Chidambaram Stadium,Nigel Llong,Nitin Menon,Ian Gould
753,11413,2019,Visakhapatnam,08/05/19,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,2,RR Pant,ACA-VDCA Stadium,NaN,NaN,NaN
754,11414,2019,Visakhapatnam,10/05/19,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,F du Plessis,ACA-VDCA Stadium,Sundaram Ravi,Bruce Oxenford,Chettithody Shamshuddin
755,11415,2019,Hyderabad,12/05/19,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong

In [46]:
winnerdata=matchesdata[matchesdata['team1']==matchesdata['winner']]

In [47]:
winnerdata.columns

Index(['id', 'season', 'city', 'date', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'result', 'dl_applied', 'winner', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'venue', 'umpire1', 'umpire2',
       'umpire3'],
      dtype='object')

In [48]:
winner_venue=winnerdata.groupby(['team1','venue']).size().reset_index()

In [49]:

winner_venue.columns=['winningteam','venue','numberofwins']

In [50]:
winner_venue.sort_values('numberofwins',ascending=False)

,winningteam,venue,numberofwins
10,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk",23
97,Mumbai Indians,Wankhede Stadium,23
67,Kolkata Knight Riders,Eden Gardens,20
38,Delhi Daredevils,Feroz Shah Kotla,17
123,Royal Challengers Bangalore,M Chinnaswamy Stadium,16
142,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal",11
112,Rajasthan Royals,Sawai Mansingh Stadium,10
57,Kings XI Punjab,"Punjab Cricket Association Stadium, Mohali",8
81,Mumbai Indians,Eden Gardens,5
49,Kings XI Punjab,Himachal Pradesh Cricket Association Stadium,4
111,Rajasthan Royals,"Sardar Patel Stadium, Motera",4
56,Kings XI Punjab,"Punjab Cricket Association IS Bindra Stadium, ...",4
79,Mumbai Indians,Dr DY Patil Sports Academy,4
63,Kings XI Punjab,Wankhede Stadium,4
20,Deccan Chargers,Barabati Stadium,3
121,Royal Challengers Bangalore,Feroz Shah Kotla,3
77,Mumbai Indians,Brabourne Stadium,3
135,Sunrisers Hyderabad,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,3
91,Mumbai Indians,"Rajiv Gandhi International Stadium, Uppal",3
8,Chennai Super Kings,M Chinnaswamy Stadium,3
9,Chennai Super Kings,M. A. Chidambaram Stadium,3
75,Kolkata Knight Riders,Subrata Roy Sahara Stadium,3
22,Deccan Chargers,Feroz Shah Kotla,2
50,Kings XI Punjab,IS Bindra Stadium,2
119,Rising Pune Supergiant,Wankhede Stadium,2
70,Kolkata Knight Riders,M Chinnaswamy Stadium,2
101,Pune Warriors,Subrata Roy Sahara Stadium,2
143,Sunrisers Hyderabad,Rajiv Gandhi Intl. Cricket Stadium,2
103,Rajasthan Royals,Brabourne Stadium,2
84,Mumbai Indians,M Chinnaswamy Stadium,2
...,...,...,...
42,Delhi Daredevils,Nehru Stadium,1
88,Mumbai Indians,Newlands,1
65,Kochi Tuskers Kerala,Nehru Stadium,1
87,Mumbai Indians,"MA Chidambaram Stadium, Chepauk",1
86,Mumbai Indians,M. Chinnaswamy Stadium,1
85,Mumbai Indians,M. A. Chidambaram Stadium,1
83,Mumbai Indians,Feroz Shah Kotla Ground,1
80,Mumbai Indians,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,1
78,Mumbai Indians,Buffalo Park,1
76,Kolkata Knight Riders,Wankhede Stadium,1
73,Kolkata Knight Riders,Sharjah Cricket Stadium,1
71,Kolkata Knight Riders,"Punjab Cricket Association Stadium, Mohali",1
69,Kolkata Knight Riders,Holkar Cricket Stadium,1
68,Kolkata Knight Riders,Feroz Shah Kotla,1
66,Kolkata Knight Riders,Dr DY Patil Sports Academy,1
64,Kochi Tuskers Kerala,Eden Gardens,1
43,Delhi Daredevils,OUTsurance Oval,1
62,Kings XI Punjab,Sheikh Zayed Stadium,1
61,Kings XI Punjab,Sharjah Cricket Stadium,1
60,Kings XI Punjab,Sawai Mansingh Stadium,1
58,Kings XI Punjab,"Rajiv Gandhi International Stadium, Uppal",1
55,Kings XI Punjab,Newlands,1
54,Kings XI Punjab,New Wanderers Stadium,1
51,Kings XI Punjab,Kingsmead,1
48,Kings XI Punjab,Feroz Shah Kotla,1
47,Kings XI Punjab,Eden Gardens,1
46,Kings XI Punjab,Barabati Stadium,1
45,Gujarat Lions,Feroz Shah Kotla,1
44,Delhi Daredevils,Shaheed Veer Narayan Singh International Stadium,1
148,Sunrisers Hyderabad,Wankhede Stadium,1

In [51]:
winner_toss=winnerdata.groupby(['winner','toss_winner']).size().reset_index()

In [52]:
winner_toss.sort_values(0,ascending=False)

                         winner                  toss_winner   0
0           Chennai Super Kings          Chennai Super Kings  30
54               Mumbai Indians               Mumbai Indians  25
66             Rajasthan Royals             Rajasthan Royals  15
44        Kolkata Knight Riders        Kolkata Knight Riders  15
11              Deccan Chargers              Deccan Chargers  11
20             Delhi Daredevils             Delhi Daredevils  11
81  Royal Challengers Bangalore  Royal Challengers Bangalore   9
90          Sunrisers Hyderabad          Sunrisers Hyderabad   8
51               Mumbai Indians             Delhi Daredevils   7
34              Kings XI Punjab              Kings XI Punjab   6
84          Sunrisers Hyderabad              Kings XI Punjab   6
36              Kings XI Punjab               Mumbai Indians   6
8           Chennai Super Kings             Rajasthan Royals   5
75  Royal Challengers Bangalore              Kings XI Punjab   5
57               Mumbai Indians  Royal Challengers Bangalore   5
47        Kolkata Knight Riders  Royal Challengers Bangalore   5
37              Kings XI Punjab             Rajasthan Royals   5
49               Mumbai Indians          Chennai Super Kings   5
64             Rajasthan Royals              Kings XI Punjab   4
85          Sunrisers Hyderabad        Kolkata Knight Riders   4
35              Kings XI Punjab        Kolkata Knight Riders   4
73  Royal Challengers Bangalore             Delhi Daredevils   4
53               Mumbai Indians        Kolkata Knight Riders   4
32              Kings XI Punjab             Delhi Daredevils   4
43        Kolkata Knight Riders              Kings XI Punjab   4
63             Rajasthan Royals             Delhi Daredevils   4
29              Kings XI Punjab          Chennai Super Kings   4
56               Mumbai Indians             Rajasthan Royals   4
65             Rajasthan Royals        Kolkata Knight Riders   4
3           Chennai Super Kings             Delhi Daredevils   4
..                          ...                          ...  ..
33              Kings XI Punjab                Gujarat Lions   2
10          Chennai Super Kings          Sunrisers Hyderabad   2
79  Royal Challengers Bangalore             Rajasthan Royals   1
76  Royal Challengers Bangalore        Kolkata Knight Riders   1
83          Sunrisers Hyderabad          Chennai Super Kings   1
2           Chennai Super Kings               Delhi Capitals   1
80  Royal Challengers Bangalore      Rising Pune Supergiants   1
70       Rising Pune Supergiant          Sunrisers Hyderabad   1
72  Royal Challengers Bangalore              Deccan Chargers   1
18             Delhi Daredevils          Chennai Super Kings   1
61                Pune Warriors               Mumbai Indians   1
60                Pune Warriors        Kolkata Knight Riders   1
21             Delhi Daredevils              Kings XI Punjab   1
24             Delhi Daredevils                Pune Warriors   1
25             Delhi Daredevils             Rajasthan Royals   1
26             Delhi Daredevils       Rising Pune Supergiant   1
28                Gujarat Lions             Delhi Daredevils   1
31              Kings XI Punjab               Delhi Capitals   1
17               Delhi Capitals          Sunrisers Hyderabad   1
16               Delhi Capitals               Mumbai Indians   1
15               Delhi Capitals               Delhi Capitals   1
39              Kings XI Punjab          Sunrisers Hyderabad   1
1           Chennai Super Kings              Deccan Chargers   1
46        Kolkata Knight Riders             Rajasthan Royals   1
9           Chennai Super Kings  Royal Challengers Bangalore   1
13              Deccan Chargers         Kochi Tuskers Kerala   1
55               Mumbai Indians                Pune Warriors   1
58               Mumbai Indians          Sunrisers Hyderabad   1
59                Pune Warriors             Delhi Daredevils   1
4           Chennai Super Kings              Kings XI Punjab   1

[91 rows x 3 columns]

In [53]:
winner_toss=winnerdata.groupby(['winner','toss_winner','toss_decision','venue']).size().reset_index()

In [54]:
winner_toss.sort_values([0],ascending=False).head(10)

,winner,toss_winner,toss_decision,venue,0
8,Chennai Super Kings,Chennai Super Kings,bat,"MA Chidambaram Stadium, Chepauk",15
104,Kolkata Knight Riders,Kolkata Knight Riders,bat,Eden Gardens,9
142,Mumbai Indians,Mumbai Indians,bat,Wankhede Stadium,9
53,Delhi Daredevils,Delhi Daredevils,bat,Feroz Shah Kotla,7
173,Rajasthan Royals,Rajasthan Royals,bat,Sawai Mansingh Stadium,5
125,Mumbai Indians,Delhi Daredevils,field,Wankhede Stadium,3
102,Kolkata Knight Riders,Kings XI Punjab,field,Eden Gardens,3
89,Kings XI Punjab,Mumbai Indians,field,Wankhede Stadium,3
115,Kolkata Knight Riders,Sunrisers Hyderabad,field,Eden Gardens,3
108,Kolkata Knight Riders,Kolkata Knight Riders,bat,Subrata Roy Sahara Stadium,3

Chennai Super Kings is the most succesful team winning most of their matches at Chennai after winning the toss and deciding to bat

More to follow